//AutoPath : Chores.DAL/ChoreDAL.generated.cs
/* THIS CODE WAS GENERATED BY A TOOL (Codification) */
/* DO NOT EDIT BY HAND - Instead edit the other partial class called ChoreDAL */
using System;
using System.Linq;
using System.Collections.Generic;
using Chores.Entities;

namespace Chores.DAL
{
	public partial class ChoreDAL
	{
	
		ChoresDB db = ChoresDB.Instance();
	
		public Chore _Get(int id)
		{
			return (from e in db.Chores where e.ID == id select e).FirstOrDefault();
		}

		public List<Chore> _List()
		{
			return db.Chores;
		}

		public int _Save(Chore entity)
		{
			if (RecordExists(entity.ID))
			{
				return Update(entity);
			}
			else
			{
				return Create(entity);
			}
		}
		
		private bool _RecordExists(int id)
		{
			return _Get(id) != null;
		}

		public int _Create(Chore entity)
		{
			entity.ID = db.Chores.Count + 1;
			db.Chores.Add(entity);
			db.Save();
			return entity.ID;
		}
		
		public int _Update(Chore entity)
		{
			Chore e = _Get(entity.ID);
			e.ChoreID = entity.ChoreID;
			e.Name = entity.Name;
			e.Description = entity.Description;
			e.Frequency = entity.Frequency;
			e.LastDoneDate = entity.LastDoneDate;
			e.LastDonePersonID = entity.LastDonePersonID;
			
			db.Save();
			return e.ID;
		}
		
		public void _Delete(int id)
		{
			Chore e = _Get(id);
			if (e != null)
			{
				db.Chores.Remove(e);
				db.Save();
			}
		}
		
	}
	
}
	