//AutoPath : Controllers/Chore/ChoreController.cs
/* THIS CODE WAS GENERATED BY A TOOL (Codification) */
/* DO NOT EDIT BY HAND - Instead create another partial class called ChoreController */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Chores.Entities;

namespace ChoresUI.Controllers
{
	public class ChoreController : Controller
	{
	
		public ViewResult Index()
		{
			return View("Chores");
		}
		
		public ViewResult Chores()
		{
			return View();
		}
		
		public ViewResult View(int id)
		{
			ViewBag.ChoreID = id;
			return View();
		}

	}

}
	