//AutoPath : Chores.BLL/PersonBLL.generated.cs
/* THIS CODE WAS GENERATED BY A TOOL (Codification) */
/* DO NOT EDIT BY HAND - Instead edit the other partial class called PersonBLL */
using System;
using System.Linq;
using System.Collections.Generic;
using Chores.Entities;
using Chores.DAL;

namespace Chores.BLL
{
	public partial class PersonBLL
	{
		
		internal Person _Get(int id)
		{
			return new Chores.DAL.PersonDAL().Get(id);
		}
		
		internal List<Person> _List()
		{
			return new Chores.DAL.PersonDAL().List();
		}

		internal int _Create(Person e)
		{
			return new Chores.DAL.PersonDAL().Create(e);
		}

		internal int _Save(Person e)
		{
			return new Chores.DAL.PersonDAL().Save(e);
		}

		internal int _Update(Person e)
		{
			return new Chores.DAL.PersonDAL().Update(e);
		}

		internal void _Delete(int id)
		{
			new Chores.DAL.PersonDAL().Delete(id);
		}

	}

}
	