//AutoPath : Chores.Entities/Chore.generated.cs
/* THIS CODE WAS GENERATED BY A TOOL (Codification) */
/* DO NOT EDIT BY HAND - Instead edit the other partial class called Chore */
using System;
using System.Linq;
using System.Collections.Generic;

namespace Chores.Entities
{
	public partial class Chore
	{
	
		public int ID
		{
			get
			{
				return ChoreID;
			}
			set
			{
				ChoreID = value;
			}
		}
		
		public int ChoreID { get; set; }
		
		public string Name { get; set; }
		
		public string Description { get; set; }
		
		public int Frequency { get; set; }
		
		public DateTime? LastDoneDate { get; set; }
		
		public string LastDoneDateString 
		{ 
			get
			{
				return LastDoneDate != null && LastDoneDate > DateTime.MinValue ? ((DateTime)LastDoneDate).ToString("dd MMM") : "-";
			}
			set
			{
				if (value != "-") { LastDoneDate = DateTime.Parse(value); }
			}
		}
		
		public int? LastDonePersonID { get; set; }
		
	}
}
	