//AutoPath : Chores.Entities/Person.generated.cs
/* THIS CODE WAS GENERATED BY A TOOL (Codification) */
/* DO NOT EDIT BY HAND - Instead edit the other partial class called Person */
using System;
using System.Linq;
using System.Collections.Generic;

namespace Chores.Entities
{
	public partial class Person
	{
	
		public int ID
		{
			get
			{
				return PersonID;
			}
			set
			{
				PersonID = value;
			}
		}
		
		public int PersonID { get; set; }
		
		public string Name { get; set; }
		
	}
}
	