//AutoPath : Controllers/api/ChoreAPIController.cs
/* THIS CODE WAS GENERATED BY A TOOL (Codification) */
/* DO NOT EDIT BY HAND - Instead edit the other partial class called ChoreDAL */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Chores.BLL;
using Chores.Entities;

namespace ChoresUI.Controllers
{

	[Route("api/[controller]")]
	public class ChoreAPIController : Controller
    {

		ChoreBLL bll = new ChoreBLL();

		// GET api/memberapi
		[HttpGet]
		public List<Chore> Get()
        {
			return bll.List();
        }

        // GET api/Choreapi/5
		[HttpGet("{id}")]
		public Chore Get(int id)
        {
			if (id == 0) { return new Chore(); }
			return bll.Get(id);
        }

        // POST api/Choreapi
		[HttpPost]
		public void Post([FromBody]Chore value)
        {
			bll.Create(value);
        }

        // PUT api/Choreapi/5
		[HttpPut("{id}")]
		public void Put(int id, [FromBody]Chore value)
        {
			value.ID = id;
			bll.Update(value);
        }

        // DELETE api/Choreapi/5
		[HttpDelete("{id}")]
        public void Delete(int id)
        {
			bll.Delete(id);
        }
    }
	
}
	