//AutoPath : Controllers/api/ChoreAPIController.cs
/* THIS CODE WAS GENERATED BY A TOOL (Codification) */
/* DO NOT EDIT BY HAND - Instead edit the other partial class called ChoreDAL */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Chores.BLL;
using Chores.Entities;

namespace ChoresUI.Controllers
{

	[Route("api/[controller]")]
	public class DueChoreAPIController : Controller
    {

		ChoreBLL bll = new ChoreBLL();

		// GET api/memberapi
		[HttpGet]
		public List<Chore> Get()
        {
			return bll.ListDue();
        }

    }
	
}
	