//AutoPath : Controllers/api/PersonAPIController.cs
/* THIS CODE WAS GENERATED BY A TOOL (Codification) */
/* DO NOT EDIT BY HAND - Instead edit the other partial class called PersonDAL */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Chores.BLL;
using Chores.Entities;

namespace ChoresUI.Controllers
{

	[Route("api/[controller]")]
	public class PersonAPIController : Controller
    {

		PersonBLL bll = new PersonBLL();

		// GET api/memberapi
		[HttpGet]
		public List<Person> Get()
        {
			return bll.List();
        }

        // GET api/Personapi/5
		[HttpGet("{id}")]
		public Person Get(int id)
        {
			if (id == 0) { return new Person(); }
			return bll.Get(id);
        }

        // POST api/Personapi
		[HttpPost]
		public void Post([FromBody]Person value)
        {
			bll.Create(value);
        }

        // PUT api/Personapi/5
		[HttpPut("{id}")]
		public void Put(int id, [FromBody]Person value)
        {
			value.ID = id;
			bll.Update(value);
        }

        // DELETE api/Personapi/5
		[HttpDelete("{id}")]
        public void Delete(int id)
        {
			bll.Delete(id);
        }
    }
	
}
	