//AutoPath : Controllers/Person/PersonController.cs
/* THIS CODE WAS GENERATED BY A TOOL (Codification) */
/* DO NOT EDIT BY HAND - Instead create another partial class called PersonController */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Chores.Entities;

namespace ChoresUI.Controllers
{
	public class PersonController : Controller
	{
	
		public ViewResult Index()
		{
			return View("Persons");
		}
		
		public ViewResult Persons()
		{
			return View();
		}
		
		public ViewResult View(int id)
		{
			ViewBag.PersonID = id;
			return View();
		}

	}

}
	